//
// Created by acco on 7/23/18.
//

#ifndef GSTTRP_GLOBALS_HPP
#define GSTTRP_GLOBALS_HPP

#define TOLERANCE (0.01f)

#define MDVRP_ROUTE_EXCESS_PENALTY (999999)

#define SUB_ROUTES_SEGMENTS_SWAP_MAX_LENGTH (5)

#define SET_PARTITIONING_MAX_POOL_SIZE (100000)

#define SET_PARTITIONING_POOL_RESERVED_SPACE (50)


#endif //GSTTRP_GLOBALS_HPP
